name: Deploy
on:
  push:
    branches:
      - main
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p 2876 2.24.130.95 >> ~/.ssh/known_hosts
      - name: Push to production
        if: github.ref == 'refs/heads/main'
        run: |
          git remote add production ssh://deploy@2.24.130.95:2876/git/countdown.findmeonline.online.git
          GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" git push production HEAD:main --force-with-lease
      - name: Push to staging
        if: github.ref == 'refs/heads/staging'
        run: |-
          git remote add staging ssh://deploy@2.24.130.95:2876/git/countdown.findmeonline.online.git
          GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" git push staging HEAD:main --force-with-lease
